#!/bin/bash
# Simple test - one scenario with full output

echo "================================================================================"
echo "US-044 AUTO-OPTIMIZATION TEST - Single Scenario"
echo "================================================================================"
echo "Testing: Low RRIF with rrif-first strategy (should auto-switch to tfsa-first)"
echo

curl -s -X POST "http://localhost:8000/api/run-simulation" \
  -H "Content-Type: application/json" \
  -d '{
    "province": "ON",
    "start_year": 2026,
    "end_age": 95,
    "strategy": "rrif-first",
    "spending_go_go": 80000,
    "go_go_end_age": 75,
    "spending_slow_go": 60000,
    "slow_go_end_age": 85,
    "spending_no_go": 50000,
    "spending_inflation": 2.5,
    "general_inflation": 2.0,
    "tfsa_room_annual_growth": 7000,
    "gap_tolerance": 1000,
    "reinvest_nonreg_dist": false,
    "income_split_rrif_fraction": 0.0,
    "hybrid_rrif_topup_per_person": 0,
    "stop_on_fail": false,
    "p1": {
      "name": "Test Person 1",
      "start_age": 65,
      "cpp_start_age": 65,
      "cpp_annual_at_start": 12000,
      "oas_start_age": 65,
      "oas_annual_at_start": 8000,
      "pension_incomes": [],
      "other_incomes": [],
      "tfsa_balance": 150000,
      "rrif_balance": 100000,
      "rrsp_balance": 0,
      "nonreg_balance": 80000,
      "corporate_balance": 0,
      "nonreg_acb": 64000,
      "nr_cash": 8000,
      "nr_gic": 16000,
      "nr_invest": 56000,
      "y_nr_cash_interest": 2.0,
      "y_nr_gic_interest": 3.5,
      "y_nr_inv_total_return": 6.0,
      "y_nr_inv_elig_div": 2.0,
      "y_nr_inv_nonelig_div": 0.5,
      "y_nr_inv_capg": 3.0,
      "y_nr_inv_roc_pct": 0.5,
      "nr_cash_pct": 10.0,
      "nr_gic_pct": 20.0,
      "nr_invest_pct": 70.0,
      "corp_cash_bucket": 0,
      "corp_gic_bucket": 0,
      "corp_invest_bucket": 0,
      "corp_rdtoh": 0,
      "y_corp_cash_interest": 2.0,
      "y_corp_gic_interest": 3.5,
      "y_corp_inv_total_return": 6.0,
      "y_corp_inv_elig_div": 2.0,
      "y_corp_inv_capg": 3.5,
      "corp_cash_pct": 5.0,
      "corp_gic_pct": 10.0,
      "corp_invest_pct": 85.0,
      "corp_dividend_type": "eligible",
      "tfsa_room_start": 7000,
      "tfsa_contribution_annual": 0,
      "enable_early_rrif_withdrawal": false,
      "early_rrif_withdrawal_start_age": 65,
      "early_rrif_withdrawal_end_age": 70,
      "early_rrif_withdrawal_annual": 20000,
      "early_rrif_withdrawal_percentage": 5.0,
      "early_rrif_withdrawal_mode": "fixed"
    },
    "p2": {
      "name": "",
      "start_age": 65,
      "cpp_start_age": 65,
      "cpp_annual_at_start": 15000,
      "oas_start_age": 65,
      "oas_annual_at_start": 8500,
      "pension_incomes": [],
      "other_incomes": [],
      "tfsa_balance": 0,
      "rrif_balance": 0,
      "rrsp_balance": 0,
      "nonreg_balance": 0,
      "corporate_balance": 0,
      "nonreg_acb": 0,
      "nr_cash": 0,
      "nr_gic": 0,
      "nr_invest": 0,
      "y_nr_cash_interest": 2.0,
      "y_nr_gic_interest": 3.5,
      "y_nr_inv_total_return": 6.0,
      "y_nr_inv_elig_div": 2.0,
      "y_nr_inv_nonelig_div": 0.5,
      "y_nr_inv_capg": 3.0,
      "y_nr_inv_roc_pct": 0.5,
      "nr_cash_pct": 10.0,
      "nr_gic_pct": 20.0,
      "nr_invest_pct": 70.0,
      "corp_cash_bucket": 0,
      "corp_gic_bucket": 0,
      "corp_invest_bucket": 0,
      "corp_rdtoh": 0,
      "y_corp_cash_interest": 2.0,
      "y_corp_gic_interest": 3.5,
      "y_corp_inv_total_return": 6.0,
      "y_corp_inv_elig_div": 2.0,
      "y_corp_inv_capg": 3.5,
      "corp_cash_pct": 5.0,
      "corp_gic_pct": 10.0,
      "corp_invest_pct": 85.0,
      "corp_dividend_type": "eligible",
      "tfsa_room_start": 7000,
      "tfsa_contribution_annual": 0,
      "enable_early_rrif_withdrawal": false,
      "early_rrif_withdrawal_start_age": 65,
      "early_rrif_withdrawal_end_age": 70,
      "early_rrif_withdrawal_annual": 20000,
      "early_rrif_withdrawal_percentage": 5.0,
      "early_rrif_withdrawal_mode": "fixed"
    }
  }' | python3 parse_optimization_result.py

echo
echo "================================================================================"
echo "Test complete"
echo "================================================================================"
